LIB = ../../libft.a

all: memset bzero memcpy memccpy memmove memchr memcmp strlen strdup strcpy strncpy strcat strncat strlcat strchr strrchr strstr strcmp strncmp atoi isalpha isdigit isalnum isascii isprint toupper tolower memalloc memdel strnew strdel strclr striter striteri strmap strmapi strequ strnequ strnequ strsub strjoin strtrim
memset:
	rm -f build/test_memset
	gcc $(LIB) tests/test_ft_memset.c  ../src/unity.c -o build/test_memset
	./build/test_memset

bzero:
	rm -f build/test_bzero
	gcc $(LIB) tests/test_ft_bzero.c ../src/unity.c -o build/test_bzero
	./build/test_bzero

memcpy:
	rm -f build/test_memcpy
	gcc $(LIB) tests/test_ft_memcpy.c  ../src/unity.c -o build/test_memcpy
	./build/test_memcpy

memccpy:
	rm -f build/test_memccpy
	gcc $(LIB) tests/test_ft_memccpy.c  ../src/unity.c -o build/test_memccpy
	./build/test_memccpy

memmove:
	rm -f build/test_memmove
	gcc $(LIB) tests/test_ft_memmove.c  ../src/unity.c -o build/test_memmove
	./build/test_memmove

memchr:
	rm -f build/test_memchr
	gcc $(LIB) tests/test_ft_memchr.c  ../src/unity.c -o build/test_memchr
	./build/test_memchr

memcmp:
	rm -f build/test_memcmp
	gcc $(LIB) tests/test_ft_memcmp.c  ../src/unity.c -o build/test_memcmp
	./build/test_memcmp

strlen:
	rm -f build/test_strlen
	gcc $(LIB) tests/test_ft_strlen.c  ../src/unity.c -o build/test_strlen
	./build/test_strlen

strdup:
	rm -f build/test_strdup
	gcc $(LIB) tests/test_ft_strdup.c  ../src/unity.c -o build/test_strdup
	./build/test_strdup

strcpy:
	rm -f build/test_strcpy
	gcc $(LIB) tests/test_ft_strcpy.c  ../src/unity.c -o build/test_strcpy
	./build/test_strcpy

strncpy:
	rm -f build/test_strncpy
	gcc $(LIB) tests/test_ft_strncpy.c  ../src/unity.c -o build/test_strncpy
	./build/test_strncpy

strcat:
	rm -f build/test_strcat
	gcc $(LIB) tests/test_ft_strcat.c  ../src/unity.c -o build/test_strcat
	./build/test_strcat

strncat:
	rm -f build/test_strncat
	gcc $(LIB) tests/test_ft_strncat.c  ../src/unity.c -o build/test_strncat
	./build/test_strncat

strlcat:
	rm -f build/test_strlcat
	gcc $(LIB) tests/test_ft_strlcat.c  ../src/unity.c -o build/test_strlcat
	./build/test_strlcat

strchr:
	rm -f build/test_strchr
	gcc $(LIB) tests/test_ft_strchr.c  ../src/unity.c -o build/test_strchr
	./build/test_strchr

strrchr:
	rm -f build/test_strrchr
	gcc $(LIB) tests/test_ft_strrchr.c  ../src/unity.c -o build/test_strrchr
	./build/test_strrchr

strstr:
	rm -f build/test_strstr
	gcc $(LIB) tests/test_ft_strstr.c  ../src/unity.c -o build/test_strstr
	./build/test_strstr

strcmp:
	rm -f build/test_strcmp
	gcc $(LIB) tests/test_ft_strcmp.c  ../src/unity.c -o build/test_strcmp
	./build/test_strcmp

strncmp:
	rm -f build/test_strncmp
	gcc $(LIB) tests/test_ft_strncmp.c  ../src/unity.c -o build/test_strncmp
	./build/test_strncmp

atoi:
	rm -f build/test_atoi
	gcc $(LIB) tests/test_ft_atoi.c  ../src/unity.c -o build/test_atoi
	./build/test_atoi

isalpha:
	rm -f build/test_isalpha
	gcc $(LIB) tests/test_ft_isalpha.c  ../src/unity.c -o build/test_isalpha
	./build/test_isalpha

isdigit:
	rm -f build/test_isdigit
	gcc $(LIB) tests/test_ft_isdigit.c  ../src/unity.c -o build/test_isdigit
	./build/test_isdigit

isalnum:
	rm -f build/test_isalnum
	gcc $(LIB) tests/test_ft_isalnum.c  ../src/unity.c -o build/test_isalnum
	./build/test_isalnum

isascii:
	rm -f build/test_isascii
	gcc $(LIB) tests/test_ft_isascii.c  ../src/unity.c -o build/test_isascii
	./build/test_isascii

isprint:
	rm -f build/test_isprint
	gcc $(LIB) tests/test_ft_isprint.c  ../src/unity.c -o build/test_isprint
	./build/test_isprint

toupper:
	rm -f build/test_toupper
	gcc $(LIB) tests/test_ft_toupper.c  ../src/unity.c -o build/test_toupper
	./build/test_toupper

tolower:
	rm -f build/test_tolower
	gcc $(LIB) tests/test_ft_tolower.c  ../src/unity.c -o build/test_tolower
	./build/test_tolower

memalloc:
	rm -f build/test_memalloc
	gcc $(LIB) tests/test_ft_memalloc.c  ../src/unity.c -o build/test_memalloc
	./build/test_memalloc

memdel:
	rm -f build/test_memdel
	gcc $(LIB) tests/test_ft_memdel.c  ../src/unity.c -o build/test_memdel
	./build/test_memdel

strnew:
	rm -f build/test_strnew
	gcc $(LIB) tests/test_ft_strnew.c  ../src/unity.c -o build/test_strnew
	./build/test_strnew

strdel:
	rm -f build/test_strdel
	gcc $(LIB) tests/test_ft_strdel.c  ../src/unity.c -o build/test_strdel
	./build/test_strdel

strclr:
	rm -f build/test_strclr
	gcc $(LIB) tests/test_ft_strclr.c  ../src/unity.c -o build/test_strclr
	./build/test_strclr

striter:
	rm -f build/test_striter
	gcc $(LIB) tests/test_ft_striter.c  ../src/unity.c -o build/test_striter
	./build/test_striter

striteri:
	rm -f build/test_striteri
	gcc $(LIB) tests/test_ft_striteri.c  ../src/unity.c -o build/test_striteri
	./build/test_striteri

strmap:
	rm -f build/test_strmap
	gcc $(LIB) tests/test_ft_strmap.c  ../src/unity.c -o build/test_strmap
	./build/test_strmap

strmapi:
	rm -f build/test_strmapi
	gcc $(LIB) tests/test_ft_strmapi.c  ../src/unity.c -o build/test_strmapi
	./build/test_strmapi

strequ:
	rm -f build/test_strequ
	gcc $(LIB) tests/test_ft_strequ.c  ../src/unity.c -o build/test_strequ
	./build/test_strequ

strnequ:
	rm -f build/test_strnequ
	gcc $(LIB) tests/test_ft_strnequ.c  ../src/unity.c -o build/test_strnequ
	./build/test_strnequ

strsub:
	rm -f build/test_strsub
	gcc $(LIB) tests/test_ft_strsub.c  ../src/unity.c -o build/test_strsub
	./build/test_strsub

strjoin:
	rm -f build/test_strjoin
	gcc $(LIB) tests/test_ft_strjoin.c  ../src/unity.c -o build/test_strjoin
	./build/test_strjoin

strtrim:
	rm -f build/test_strtrim
	gcc $(LIB) tests/test_ft_strtrim.c  ../src/unity.c -o build/test_strtrim
	./build/test_strtrim

clean:
	rm -f build/*